[package]
name = "othcloud_terminal_profiles"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/othcloud_terminal_profiles.rs"
doctest = false

[dependencies]
gpui.workspace = true
log.workspace = true
othcloud_client.workspace = true
picker.workspace = true
terminal.workspace = true
terminal_view.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true
